[package]
name = "udp-api"
version = "0.1.0"
edition = "2024"

[dependencies]
nprpc = { path = "../../nprpc", default-features = false }
serde = { version = "1.0.229", default-features = false, features = ["derive"] }
postcard-schema-ng.workspace = true
postcard.workspace = true

[dev-dependencies]
insta = "1.48.0"

[features]
default = ["std"]
std = [
    "postcard-schema-ng/use-std",
    "nprpc/std",
]
