[package]
name = "demo-api"
version = "0.1.0"
edition = "2024"

[dependencies]
nprpc.path = "../../nprpc"
serde = { version = "1.0.229", default-features = false, features = ["derive"] }
postcard-schema-ng.workspace = true
postcard.workspace = true

[features]
default = ["std"]
std = ["postcard-schema-ng/use-std"]
